name: check-lan CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu' || 'x86_64-unknown-linux-gnu' }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
    
    - name: Sentry Test Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        ./target/debug/check-lan 192.168.100.1 255.255.255.0 0 &> output.log
        if [ ! -s output.log ]; then
          echo "No output found in output.log"
          exit 1
        fi
        cat output.log

    - name: Sentry Test Windows
      if: matrix.os == 'windows-latest'
      run: |
        ./target/debug/check-lan.exe 192.168.100.1 255.255.255.0 0 *> output.log
        if (-not (Get-Content output.log)) {
          Write-Error "No output found in output.log"
          exit 1
        }
        Get-Content output.log
